/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as ResourcesSpecsRouteImport } from './routes/resources.specs'
import { Route as ResourcesGuidesRouteImport } from './routes/resources.guides'
import { Route as ProductsWireRodsRouteImport } from './routes/products.wire-rods'
import { Route as ProductsSheetsCoilsRouteImport } from './routes/products.sheets-coils'
import { Route as ProductsProfilesBarsRouteImport } from './routes/products.profiles-bars'
import { Route as ProductsPipesRouteImport } from './routes/products.pipes'
import { Route as ProductsIngotsRouteImport } from './routes/products.ingots'
import { Route as ProductsDiscsRouteImport } from './routes/products.discs'
import { Route as ProductsBilletsRouteImport } from './routes/products.billets'
import { Route as IndustriesSectorRouteImport } from './routes/industries.$sector'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndustriesRoute,
} as any)
const ResourcesSpecsRoute = ResourcesSpecsRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesGuidesRoute = ResourcesGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => ResourcesRoute,
} as any)
const ProductsWireRodsRoute = ProductsWireRodsRouteImport.update({
  id: '/wire-rods',
  path: '/wire-rods',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsSheetsCoilsRoute = ProductsSheetsCoilsRouteImport.update({
  id: '/sheets-coils',
  path: '/sheets-coils',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsProfilesBarsRoute = ProductsProfilesBarsRouteImport.update({
  id: '/profiles-bars',
  path: '/profiles-bars',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsPipesRoute = ProductsPipesRouteImport.update({
  id: '/pipes',
  path: '/pipes',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsIngotsRoute = ProductsIngotsRouteImport.update({
  id: '/ingots',
  path: '/ingots',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsDiscsRoute = ProductsDiscsRouteImport.update({
  id: '/discs',
  path: '/discs',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsBilletsRoute = ProductsBilletsRouteImport.update({
  id: '/billets',
  path: '/billets',
  getParentRoute: () => ProductsRoute,
} as any)
const IndustriesSectorRoute = IndustriesSectorRouteImport.update({
  id: '/$sector',
  path: '/$sector',
  getParentRoute: () => IndustriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/locations': typeof LocationsRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/industries/$sector': typeof IndustriesSectorRoute
  '/products/billets': typeof ProductsBilletsRoute
  '/products/discs': typeof ProductsDiscsRoute
  '/products/ingots': typeof ProductsIngotsRoute
  '/products/pipes': typeof ProductsPipesRoute
  '/products/profiles-bars': typeof ProductsProfilesBarsRoute
  '/products/sheets-coils': typeof ProductsSheetsCoilsRoute
  '/products/wire-rods': typeof ProductsWireRodsRoute
  '/resources/guides': typeof ResourcesGuidesRoute
  '/resources/specs': typeof ResourcesSpecsRoute
  '/industries/': typeof IndustriesIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/locations': typeof LocationsRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/industries/$sector': typeof IndustriesSectorRoute
  '/products/billets': typeof ProductsBilletsRoute
  '/products/discs': typeof ProductsDiscsRoute
  '/products/ingots': typeof ProductsIngotsRoute
  '/products/pipes': typeof ProductsPipesRoute
  '/products/profiles-bars': typeof ProductsProfilesBarsRoute
  '/products/sheets-coils': typeof ProductsSheetsCoilsRoute
  '/products/wire-rods': typeof ProductsWireRodsRoute
  '/resources/guides': typeof ResourcesGuidesRoute
  '/resources/specs': typeof ResourcesSpecsRoute
  '/industries': typeof IndustriesIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/locations': typeof LocationsRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/industries/$sector': typeof IndustriesSectorRoute
  '/products/billets': typeof ProductsBilletsRoute
  '/products/discs': typeof ProductsDiscsRoute
  '/products/ingots': typeof ProductsIngotsRoute
  '/products/pipes': typeof ProductsPipesRoute
  '/products/profiles-bars': typeof ProductsProfilesBarsRoute
  '/products/sheets-coils': typeof ProductsSheetsCoilsRoute
  '/products/wire-rods': typeof ProductsWireRodsRoute
  '/resources/guides': typeof ResourcesGuidesRoute
  '/resources/specs': typeof ResourcesSpecsRoute
  '/industries/': typeof IndustriesIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/catalog'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/industries'
    | '/locations'
    | '/privacy'
    | '/products'
    | '/projects'
    | '/quote'
    | '/resources'
    | '/sitemap.xml'
    | '/terms'
    | '/industries/$sector'
    | '/products/billets'
    | '/products/discs'
    | '/products/ingots'
    | '/products/pipes'
    | '/products/profiles-bars'
    | '/products/sheets-coils'
    | '/products/wire-rods'
    | '/resources/guides'
    | '/resources/specs'
    | '/industries/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/catalog'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/locations'
    | '/privacy'
    | '/projects'
    | '/quote'
    | '/resources'
    | '/sitemap.xml'
    | '/terms'
    | '/industries/$sector'
    | '/products/billets'
    | '/products/discs'
    | '/products/ingots'
    | '/products/pipes'
    | '/products/profiles-bars'
    | '/products/sheets-coils'
    | '/products/wire-rods'
    | '/resources/guides'
    | '/resources/specs'
    | '/industries'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/catalog'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/industries'
    | '/locations'
    | '/privacy'
    | '/products'
    | '/projects'
    | '/quote'
    | '/resources'
    | '/sitemap.xml'
    | '/terms'
    | '/industries/$sector'
    | '/products/billets'
    | '/products/discs'
    | '/products/ingots'
    | '/products/pipes'
    | '/products/profiles-bars'
    | '/products/sheets-coils'
    | '/products/wire-rods'
    | '/resources/guides'
    | '/resources/specs'
    | '/industries/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  CatalogRoute: typeof CatalogRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  LocationsRoute: typeof LocationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  QuoteRoute: typeof QuoteRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/industries/': {
      id: '/industries/'
      path: '/'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/resources/specs': {
      id: '/resources/specs'
      path: '/specs'
      fullPath: '/resources/specs'
      preLoaderRoute: typeof ResourcesSpecsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/guides': {
      id: '/resources/guides'
      path: '/guides'
      fullPath: '/resources/guides'
      preLoaderRoute: typeof ResourcesGuidesRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/products/wire-rods': {
      id: '/products/wire-rods'
      path: '/wire-rods'
      fullPath: '/products/wire-rods'
      preLoaderRoute: typeof ProductsWireRodsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/sheets-coils': {
      id: '/products/sheets-coils'
      path: '/sheets-coils'
      fullPath: '/products/sheets-coils'
      preLoaderRoute: typeof ProductsSheetsCoilsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/profiles-bars': {
      id: '/products/profiles-bars'
      path: '/profiles-bars'
      fullPath: '/products/profiles-bars'
      preLoaderRoute: typeof ProductsProfilesBarsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/pipes': {
      id: '/products/pipes'
      path: '/pipes'
      fullPath: '/products/pipes'
      preLoaderRoute: typeof ProductsPipesRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/ingots': {
      id: '/products/ingots'
      path: '/ingots'
      fullPath: '/products/ingots'
      preLoaderRoute: typeof ProductsIngotsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/discs': {
      id: '/products/discs'
      path: '/discs'
      fullPath: '/products/discs'
      preLoaderRoute: typeof ProductsDiscsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/billets': {
      id: '/products/billets'
      path: '/billets'
      fullPath: '/products/billets'
      preLoaderRoute: typeof ProductsBilletsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/industries/$sector': {
      id: '/industries/$sector'
      path: '/$sector'
      fullPath: '/industries/$sector'
      preLoaderRoute: typeof IndustriesSectorRouteImport
      parentRoute: typeof IndustriesRoute
    }
  }
}

interface IndustriesRouteChildren {
  IndustriesSectorRoute: typeof IndustriesSectorRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesSectorRoute: IndustriesSectorRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

interface ProductsRouteChildren {
  ProductsBilletsRoute: typeof ProductsBilletsRoute
  ProductsDiscsRoute: typeof ProductsDiscsRoute
  ProductsIngotsRoute: typeof ProductsIngotsRoute
  ProductsPipesRoute: typeof ProductsPipesRoute
  ProductsProfilesBarsRoute: typeof ProductsProfilesBarsRoute
  ProductsSheetsCoilsRoute: typeof ProductsSheetsCoilsRoute
  ProductsWireRodsRoute: typeof ProductsWireRodsRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsBilletsRoute: ProductsBilletsRoute,
  ProductsDiscsRoute: ProductsDiscsRoute,
  ProductsIngotsRoute: ProductsIngotsRoute,
  ProductsPipesRoute: ProductsPipesRoute,
  ProductsProfilesBarsRoute: ProductsProfilesBarsRoute,
  ProductsSheetsCoilsRoute: ProductsSheetsCoilsRoute,
  ProductsWireRodsRoute: ProductsWireRodsRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ResourcesRouteChildren {
  ResourcesGuidesRoute: typeof ResourcesGuidesRoute
  ResourcesSpecsRoute: typeof ResourcesSpecsRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesGuidesRoute: ResourcesGuidesRoute,
  ResourcesSpecsRoute: ResourcesSpecsRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  CatalogRoute: CatalogRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  LocationsRoute: LocationsRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  QuoteRoute: QuoteRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
